name: Write

on: workflow_dispatch

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install
      run: pip install -r requirements.txt
    - name: Write
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HTTPS_REMOTE_URL: 'https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/elh/fluteur'
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python write.py --pull
