name: write

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  write:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install
      run: pip install -r requirements.txt
    - name: Write
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python write.py --pull
    # Doing in the same action because Github Actions do not trigger subsequent actions
    # limitation of using automatic secrets.GITHUB_TOKEN.
    - name: Merge
      uses: "pascalgn/automerge-action@v0.15.6"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
